### ISSUE TITLE
System allows students to send POST requests to sign up for any opp block, including full ones

### ISSUE THREAD

**Issue by zminster** [johnnylindbergh/OppBlock#114]
I'm willing to gamble that a student can sign up for opp blocks by sending POST requests regardless of:

- Whether the ID of that opp block is actually legit (this will probably crash the server)
- Whether the opp block is full or not (CONFIRMED BROKEN)
- Whether the opp block exists for this opp_day or not
- Whether sign ups are allowed or not allowed

...seriously?

**Comment by zminster** [comment]
Related to #108?

**Comment by Anecdotal** [comment]
I wrote a slew of untested middlewares to solve this problem and simplify student.js and committed them to the issue branch. They should be finished and tested by the end of the week.
