### ISSUE TITLE
Implement Pages When Students Haven't Chosen

### ISSUE THREAD

**Issue by Anecdotal** [johnnylindbergh/OppBlock#30]
We need to figure out A) what the administrators/we want as the "default" Oppblock offering, then 2) Implement that in the database (making sure the default offering gets added to every Oppblock day)

**Comment by zminster** [comment]
No Default: --implement a if(choice==null) part of student page, and a message (setting?) for students who haven't signed up after their cutoff.

**Comment by Anecdotal** [comment]
Implemented
