### ISSUE TITLE
Create webpage, endpoint, & decide structure for attendance taking

### ISSUE THREAD

**Issue by Anecdotal** [johnnylindbergh/OppBlock#35]
Talk in class.

**Comment by zminster** [comment]
Absence (at oppblock) table? (Differentiate kinds of absences [didn't sign up vs. didn't go])

**Comment by zminster** [comment]
THINGS WE NEED:

-add present row to choice table
-Teacher page where they take attendance
-Admin page with table of (^present) students

**Comment by Anecdotal** [comment]
I'm assuming for now that this is done
