### ISSUE TITLE
Teacher Background Image Style

### ISSUE THREAD

**Issue by johnnylindbergh** [johnnylindbergh/OppBlock#74]
Teacher page accordion section causes the background image to resize.
Also maybe we could compress that image a little. Currently it's an absurd 15 MB that get reloaded on every page refresh.

**Comment by zminster** [comment]
Real quick - I can make this change in a few minutes, but I've found in my
experience that background images specified in css with a relative URL
always reload, whereas an absolute URL causes modern browsers to check the
cache and discover the image is already in memory.

This in conjunction with background-position would probably address this
issue request.
