### ISSUE TITLE
OFFERINGS DISAPPEARING

### ISSUE THREAD

**Issue by malymilo** [johnnylindbergh/OppBlock#96]
Teachers(Zunka, Gibson, Taylor, Clark, Nichols) created offerings and selected the dates but the offerings disappeared from all pages, teacher, student and admin. The offerings still exist in offerings table but have somehow been removed from calendar after their creation.

**Comment by zminster** [comment]
I'm the one at 2:50: https://www.youtube.com/watch?v=Q5AncCWcnnA
